# Generated by Django 2.2.7 on 2019-11-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='global_database',
            name='user',
        ),
        migrations.AddField(
            model_name='global_database',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
