# Generated by Django 2.2.7 on 2019-11-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_global_database_spam_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='global_database',
            name='Email_Address',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
